name: my_goals_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  beamer: ^1.5.3
  get_it: ^2.0.1
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  shared_preferences: ^0.5.3+4
  dio: ^4.0.6
  json_serializable: ^6.2.0
  flutter_riverpod: ^1.0.4
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  retrofit: ^3.0.1+1 
  pretty_dio_logger: ^1.1.1
  intl: ^0.17.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.9.2"

  retrofit_generator: ^4.0.1

flutter:

  uses-material-design: true

